apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dt-agent-quotes-pvc
  namespace: dt-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dt-agent-logs-pvc
  namespace: dt-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dt-agent-incoming-pvc
  namespace: dt-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

